osx_image: xcode8.3

sudo: false

language: node_js
node_js: "8"

env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - ANDROID_HOME=$HOME/android-sdk

os:
- osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds
  - $HOME/.cache/yarn
  - $HOME/android-sdk-dl
  - $HOME/android-sdk
before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.2.0/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.2.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- curl -L https://yarnpkg.com/latest.tar.gz | tar xvz
- export PATH="$HOME/.yarn/bin:$PATH"
# Download and unzip the Android SDK tools (if not already there thanks to the cache mechanism)
# Latest version available here: https://developer.android.com/studio/#command-tools
- if test ! -e $HOME/android-sdk-dl/sdk-tools.zip ; then curl https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip > $HOME/android-sdk-dl/sdk-tools.zip ; fi
- unzip -qq -n $HOME/android-sdk-dl/sdk-tools.zip -d $HOME/android-sdk

# Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
- echo y | $HOME/android-sdk/tools/bin/sdkmanager 'tools' > /dev/null
- echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platform-tools' > /dev/null
- echo y | $HOME/android-sdk/tools/bin/sdkmanager 'build-tools;27.0.3' > /dev/null
- echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-27' > /dev/null
- echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;google;m2repository' > /dev/null

install:
- yarn
- yarn global add cordova

script:
- yarn build

before_cache:
- rm -rf $HOME/.cache/electron-builder/wine

before_deploy:
# Set up git user name and tag this commit
- git config --local user.name "Michael J Feher"
- git config --local user.email "github@phearzero.com"

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: J3RkERAS4zgRE0I7d5PwhZU+aiNzqKpI43top1Zu1BDLbnxcR1F8H+FLvXwG+C4rMkxg5S5K8sZtstXXyK1tpF0ixlVUx+YWlkwz/dM02iTVFSqf4uuv6akztKDO/uRPNk1EtibVpu9IbV/KcvHLuZsHkXmW5swl19MM8+shZHMizkGGfM0u1UZPAni5Cr2r+wDOUdU1km8lHHPAI9E+yFlVNUdOWYG3hhwf7QGnDY+EoaUUbSXyNwE3Hd2epa5FiGWgC8XQBzGsdg4RdYBjWbeNmpA8jCxKQr6j3eFEyTeatlUW3aUt8DcPmuZT6iD+fME2PlGxbE06Esq7tSXKcuN2MaQxWGgGQ17eXUTPB68maCeFtHxLN0YrsL1FovvPT86AoqDVw3ohkcL1miqR4eW/Ewl6U8uM6/Gc4nAnnm0+bBrcgy5/3Id62OjDuBfGC4EYYHyEzaPvW9+KpbBsl6p2qjmXHREn++Jh3qrGQGLwbGY0wEA1HOYIPwI14Ag+1yEqCiNe8neZVAJow264Khk4U3DoH/2nmk6fmalgDCdC10jcg8Ob5RTdX70/VYly0PLKXaPNeTtw9HSg3f0tG8HfiQm5E38ZVyFZtKm2bjk6SslOZWDiVjXiMncVGEPBrMQudQn6HkW4tyUeLBV2hHAVW2Y6WWyUVhiDNpZOT7o=
  file_glob: true
  file: dist/*.zip
  on:
    branches: master
